spring:
  application:
    name: Blog_project

  datasource:
    url: jdbc:mysql://localhost:3306/Blog
    username: dltnswn20
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secretKey: 30295222WNGUSSLADPTJDSLARHAKDNJDY1085239838
  refreshKey: 30295222WNGUSSLADPTJDSLARHAKDNJDY1085239838

server:
  port: 8080